### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by princed** [princed/postcss-modules-values-replace#2]
See start in https://github.com/princed/postcss-modules-values-replace/issues/1#issuecomment-262766354

**Comment by princed** [comment]
@kumarharsh Let's move here.

Could you please show how do use @value in your css?

**Comment by kumarharsh** [comment]
I'm using @value like this:
```css
/* src/css/shared/colors.css */
@value mainBg: #456371;
```
```css
/* src/modules/page/page.css */
@value mainBg from "css/shared/colors";  /* using webpack's resolve.moduleDirectory */

.page {
  background-color: mainBg;
  color: color(mainBg lightness(+30%));
}
```
