### ISSUE TITLE
How to remove values completely?

### ISSUE THREAD

**Issue by Diokuz** [princed/postcss-modules-values-replace#27]
postcss-modules-values-replace replaces values in sheets but leaves them in the head of file, so after compilation I have:

```css
@value spacing2XS from '@platform-ui-mobile/spacing/spacing.css';
@value spacing3XS from '@platform-ui-mobile/spacing/spacing.css';
@value colorLightBlue100 from '@platform-ui-mobile/colors/primitives.css';
@value colorLightBlue300 from '@platform-ui-mobile/colors/primitives.css';
@value colorBlue300 from '@platform-ui-mobile/colors/primitives.css';
@value colorYellow100 from '@platform-ui-mobile/colors/primitives.css';
@value colorGray400 from '@platform-ui-mobile/colors/primitives.css';
@value colorBlack300 from '@platform-ui-mobile/colors/primitives.css';
@value colorWhite100 from '@platform-ui-mobile/colors/primitives.css';
@value colorGray100 from '@platform-ui-mobile/colors/primitives.css';

.wrapper {
    width: 100%;
    display: flex;
    justify-content: center;
    height: 24px;
}
...
```

How to remove them completely? I dont want to ship my npm package with this useless code.
